# Generated by Django 4.0.4 on 2022-05-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_permissions_userprojectpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='permission_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
