# Generated by Django 4.0.4 on 2022-05-11 12:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_permissions_permission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprojectpermission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
